### ISSUE TITLE
Plugin compatibility/ world generation

### ISSUE THREAD

**Issue by IzzelAliz** [TorchSpigot/Torch#120]
既然是国人作者，那就中文吧233
有一个叫做Senitel的插件，是citizens的附加插件，当按照指令设置后，使用它的生物追踪功能会疯狂报错，在paper上测试无误。
第二个问题是torch的默认主世界会出现奇怪的生成错误（区块错误？），具体表现为正常地图区域出现平整的海洋区块，非常突兀，这个问题在其他任何多世界都没有出现。
最后，作者加油！很喜欢torch

**Comment by SotrForgotten** [comment]
第一个能贴下报错吗，第二个确保使用的是最新版本（如果已经是的话记得回复一下_(:зゝ∠)_

**Comment by IzzelAliz** [comment]
是最新版本，报错明天中午吧

**Comment by IzzelAliz** [comment]
咱的报错
加油，那个地图都可以缓缓，先修这个吧
`[16:39:39] [Server thread/WARN]: [Citizens] Task #78 for Citizens v2.0.21-SNAPSHOT (build 1463) generated an exception
net.minecraft.server.v1_11_R1.ReportedException: Ticking player
	at net.citizensnpcs.nms.v1_11_R1.util.NMSImpl.tick(NMSImpl.java:975) ~[?:?]
	at net.citizensnpcs.util.NMS.tick(NMS.java:265) ~[?:?]
	at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[Torchpowered-1.11.2.jar:git-Torch-"7efabb5"]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [Torchpowered-1.11.2.jar:git-Torch-"7efabb5"]
	at org.torch.server.TorchServer.updateLogicsAndPhysics(TorchServer.java:891) [Torchpowered-1.11.2.jar:git-Torch-"7efabb5"]
	at org.torch.server.TorchServer.updateLogicsPhysicsExecuteCommands(TorchServer.java:1625) [Torchpowered-1.11.2.jar:git-Torch-"7efabb5"]
	at org.torch.server.TorchServer.tick(TorchServer.java:840) [Torchpowered-1.11.2.jar:git-Torch-"7efabb5"]
	at org.torch.server.TorchServer.run(TorchServer.java:549) [Torchpowered-1.11.2.jar:git-Torch-"7efabb5"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoSuchFieldError: c
	at net.citizensnpcs.nms.v1_11_R1.util.PlayerPathfinderAbstract.a(PlayerPathfinderAbstract.java:36) ~[?:?]
	at net.citizensnpcs.nms.v1_11_R1.util.PlayerPathfinder.a(PlayerPathfinder.java:33) ~[?:?]
	at net.citizensnpcs.nms.v1_11_R1.util.PlayerPathfinder.a(PlayerPathfinder.java:26) ~[?:?]
	at net.citizensnpcs.nms.v1_11_R1.util.PlayerNavigation.a2(PlayerNavigation.java:280) ~[?:?]
	at net.citizensnpcs.nms.v1_11_R1.util.PlayerNavigation.a(PlayerNavigation.java:73) ~[?:?]
	at net.minecraft.server.v1_11_R1.NavigationAbstract.a(NavigationAbstract.java:68) ~[Torchpowered-1.11.2.jar:git-Torch-"7efabb5"]
	at net.citizensnpcs.nms.v1_11_R1.util.PlayerNavigation.a(PlayerNavigation.java:103) ~[?:?]
	at net.citizensnpcs.nms.v1_11_R1.util.NMSImpl$NavigationFieldWrapper.setPath(NMSImpl.java:1074) ~[?:?]
	at net.citizensnpcs.npc.ai.MCTargetStrategy.update(MCTargetStrategy.java:119) ~[?:?]
	at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:163) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:274) ~[?:?]
	at net.citizensnpcs.nms.v1_11_R1.entity.EntityHumanNPC.A_(EntityHumanNPC.java:140) ~[?:?]
	at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1750) ~[Torchpowered-1.11.2.jar:git-Torch-"7efabb5"]
	at net.citizensnpcs.nms.v1_11_R1.util.NMSImpl.tick(NMSImpl.java:969) ~[?:?]
	... 9 more`

**Comment by IzzelAliz** [comment]
`[13:44:34 ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_11_R1.ReportedException: Ticking player
        at org.torch.server.TorchServer.updateLogicsAndPhysics(TorchServer.java:954) ~[Torchpowered-1.11.2.jar:git-Torch-"ddb5664"]
        at org.torch.server.TorchServer.updateLogicsPhysicsExecuteCommands(TorchServer.java:1625) ~[Torchpowered-1.11.2.jar:git-Torch-"ddb5664"]
        at org.torch.server.TorchServer.tick(TorchServer.java:840) ~[Torchpowered-1.11.2.jar:git-Torch-"ddb5664"]
        at org.torch.server.TorchServer.run(TorchServer.java:549) [Torchpowered-1.11.2.jar:git-Torch-"ddb5664"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoSuchFieldError: c
        at net.citizensnpcs.nms.v1_11_R1.util.PlayerPathfinderAbstract.a(PlayerPathfinderAbstract.java:36) ~[?:?]
        at net.citizensnpcs.nms.v1_11_R1.util.PlayerPathfinder.a(PlayerPathfinder.java:33) ~[?:?]
        at net.citizensnpcs.nms.v1_11_R1.util.PlayerPathfinder.a(PlayerPathfinder.java:26) ~[?:?]
        at net.citizensnpcs.nms.v1_11_R1.util.PlayerNavigation.a2(PlayerNavigation.java:280) ~[?:?]
        at net.citizensnpcs.nms.v1_11_R1.util.PlayerNavigation.a(PlayerNavigation.java:73) ~[?:?]
        at net.minecraft.server.v1_11_R1.NavigationAbstract.a(NavigationAbstract.java:68) ~[Torchpowered-1.11.2.jar:git-Torch-"ddb5664"]
        at net.citizensnpcs.nms.v1_11_R1.util.PlayerNavigation.a(PlayerNavigation.java:103) ~[?:?]
        at net.citizensnpcs.nms.v1_11_R1.util.NMSImpl$NavigationFieldWrapper.setPath(NMSImpl.java:1104) ~[?:?]
        at net.citizensnpcs.npc.ai.MCTargetStrategy.update(MCTargetStrategy.java:119) ~[?:?]
        at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:164) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:274) ~[?:?]
        at net.citizensnpcs.nms.v1_11_R1.entity.EntityHumanNPC.A_(EntityHumanNPC.java:140) ~[?:?]
        at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1750) ~[Torchpowered-1.11.2.jar:git-Torch-"ddb5664"]
        at net.minecraft.server.v1_11_R1.World.h(World.java:1722) ~[Torchpowered-1.11.2.jar:git-Torch-"ddb5664"]
        at net.minecraft.server.v1_11_R1.WorldServer.l(WorldServer.java:657) ~[Torchpowered-1.11.2.jar:git-Torch-"ddb5664"]
        at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1508) ~[Torchpowered-1.11.2.jar:git-Torch-"ddb5664"]
        at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:633) ~[Torchpowered-1.11.2.jar:git-Torch-"ddb5664"]
        at org.torch.server.TorchServer.updateLogicsAndPhysics(TorchServer.java:944) ~[Torchpowered-1.11.2.jar:git-Torch-"ddb5664"]
        ... 4 more
[13:44:34 ERROR]:       Cause of unexpected exception was
java.lang.NoSuchFieldError: c
        at net.citizensnpcs.nms.v1_11_R1.util.PlayerPathfinderAbstract.a(PlayerPathfinderAbstract.java:36) ~[?:?]
        at net.citizensnpcs.nms.v1_11_R1.util.PlayerPathfinder.a(PlayerPathfinder.java:33) ~[?:?]
        at net.citizensnpcs.nms.v1_11_R1.util.PlayerPathfinder.a(PlayerPathfinder.java:26) ~[?:?]
        at net.citizensnpcs.nms.v1_11_R1.util.PlayerNavigation.a2(PlayerNavigation.java:280) ~[?:?]
        at net.citizensnpcs.nms.v1_11_R1.util.PlayerNavigation.a(PlayerNavigation.java:73) ~[?:?]
        at net.minecraft.server.v1_11_R1.NavigationAbstract.a(NavigationAbstract.java:68) ~[Torchpowered-1.11.2.jar:git-Torch-"ddb5664"]
        at net.citizensnpcs.nms.v1_11_R1.util.PlayerNavigation.a(PlayerNavigation.java:103) ~[?:?]
        at net.citizensnpcs.nms.v1_11_R1.util.NMSImpl$NavigationFieldWrapper.setPath(NMSImpl.java:1104) ~[?:?]
        at net.citizensnpcs.npc.ai.MCTargetStrategy.update(MCTargetStrategy.java:119) ~[?:?]
        at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:164) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:274) ~[?:?]
        at net.citizensnpcs.nms.v1_11_R1.entity.EntityHumanNPC.A_(EntityHumanNPC.java:140) ~[?:?]
        at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1750) ~[Torchpowered-1.11.2.jar:git-Torch-"ddb5664"]
        at net.minecraft.server.v1_11_R1.World.h(World.java:1722) ~[Torchpowered-1.11.2.jar:git-Torch-"ddb5664"]
        at net.minecraft.server.v1_11_R1.WorldServer.l(WorldServer.java:657) ~[Torchpowered-1.11.2.jar:git-Torch-"ddb5664"]
        at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1508) ~[Torchpowered-1.11.2.jar:git-Torch-"ddb5664"]
        at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:633) ~[Torchpowered-1.11.2.jar:git-Torch-"ddb5664"]
        at org.torch.server.TorchServer.updateLogicsAndPhysics(TorchServer.java:944) ~[Torchpowered-1.11.2.jar:git-Torch-"ddb5664"]
        at org.torch.server.TorchServer.updateLogicsPhysicsExecuteCommands(TorchServer.java:1625) ~[Torchpowered-1.11.2.jar:git-Torch-"ddb5664"]
        at org.torch.server.TorchServer.tick(TorchServer.java:840) ~[Torchpowered-1.11.2.jar:git-Torch-"ddb5664"]
        at org.torch.server.TorchServer.run(TorchServer.java:549) [Torchpowered-1.11.2.jar:git-Torch-"ddb5664"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]`
我去CircleCI下载最新构建之后的报错

**Comment by SotrForgotten** [comment]
报错已经修复

**Comment by SotrForgotten** [comment]
生成问题已修复，感谢反馈
