### ISSUE TITLE
EntityPlayer: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by SotrForgotten** [TorchSpigot/Torch#17]
> R.1.4.3

```
---- Minecraft Crash Report ----
// There are four lights!

Time: 16-7-24 下午5:42
Description: Ticking player

java.lang.ArrayIndexOutOfBoundsException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.server.v1_9_R2.EntityPlayer.k_(EntityPlayer.java:332)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.server.v1_9_R2.EntityPlayer)
	Entity ID: 59518
	Entity Name: umaruchan
	Entity's Exact location: 97.00, 66.00, -1129.00
	Entity's Block location: World: (97,66,-1129), Chunk: (at 1,4,7 in 6,-71; contains blocks 96,0,-1136 to 111,255,-1121), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,0,-1536 to 511,255,-1025)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.v1_9_R2.EntityPlayer.k_(EntityPlayer.java:332)
	at net.minecraft.server.v1_9_R2.PlayerList.disconnect(PlayerList.java:408)
	at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1107)
	at net.minecraft.server.v1_9_R2.NetworkManager.handleDisconnection(NetworkManager.java:328)
	at net.minecraft.server.v1_9_R2.ServerConnection.c(ServerConnection.java:189)
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:995)
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:408)
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:828)
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:721)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by SotrForgotten** [comment]
fixed, close this.

**Comment by SotrForgotten** [comment]
not fixed

**Comment by SotrForgotten** [comment]
Seem a plugin bug, like Chair.
