### ISSUE TITLE
Invalid bit length repeat

### ISSUE THREAD

**Issue by SotrForgotten** [TorchSpigot/Torch#21]
```
Description: Exception in server tick loop

java.lang.RuntimeException: java.util.zip.ZipException: invalid bit length repeat
	at org.bukkit.craftbukkit.v1_9_R2.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:31)
	at org.bukkit.craftbukkit.v1_9_R2.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:15)
	at org.bukkit.craftbukkit.v1_9_R2.util.AsynchronousExecutor$Task.init(AsynchronousExecutor.java:150)
	at org.bukkit.craftbukkit.v1_9_R2.util.AsynchronousExecutor$Task.initAsync(AsynchronousExecutor.java:95)
	at org.bukkit.craftbukkit.v1_9_R2.util.AsynchronousExecutor$Task.run(AsynchronousExecutor.java:85)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.zip.ZipException: invalid bit length repeat
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.torch.util.io.FastBufferedInputStream.noMoreCharacters(FastBufferedInputStream.java:187)
	at org.torch.util.io.FastBufferedInputStream.read(FastBufferedInputStream.java:200)
	at java.io.DataInputStream.readByte(DataInputStream.java:265)
	at net.minecraft.server.v1_9_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:75)
	at net.minecraft.server.v1_9_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:53)
	at net.minecraft.server.v1_9_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:43)
	at net.minecraft.server.v1_9_R2.RegionFileCache.c(RegionFileCache.java:93)
	at net.minecraft.server.v1_9_R2.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:84)
	at org.bukkit.craftbukkit.v1_9_R2.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:22)
	... 7 more
```

**Comment by SotrForgotten** [comment]
not a server bug, there is a chunk that 1.2GB.
