### ISSUE TITLE
Exception ticking world

### ISSUE THREAD

**Issue by SotrForgotten** [TorchSpigot/Torch#23]
```
[16:02:00] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_9_R2.ReportedException: Exception ticking world
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:962) ~[Torch.jar:git-Torch-unknown]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:412) ~[Torch.jar:git-Torch-unknown]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:829) ~[Torch.jar:git-Torch-unknown]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:722) [Torch.jar:git-Torch-unknown]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.IndexOutOfBoundsException: writerIndex(22598) + minWritableBytes(2048) exceeds maxCapacity(24644): UnpooledHeapByteBuf(ridx: 0, widx: 22598, cap: 24644/24644)
	at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:242) ~[Torch.jar:git-Torch-unknown]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:817) ~[Torch.jar:git-Torch-unknown]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:825) ~[Torch.jar:git-Torch-unknown]
	at net.minecraft.server.v1_9_R2.PacketDataSerializer.writeBytes(PacketDataSerializer.java:755) ~[Torch.jar:git-Torch-unknown]
	at net.minecraft.server.v1_9_R2.PacketPlayOutMapChunk.a(PacketPlayOutMapChunk.java:140) ~[Torch.jar:git-Torch-unknown]
	at com.destroystokyo.paper.antixray.AntiXray.createPacket(AntiXray.java:117) ~[Torch.jar:git-Torch-unknown]
	at net.minecraft.server.v1_9_R2.PacketPlayOutMapChunk.<init>(PacketPlayOutMapChunk.java:35) ~[Torch.jar:git-Torch-unknown]
	at net.minecraft.server.v1_9_R2.PlayerChunk.d(PlayerChunk.java:250) ~[Torch.jar:git-Torch-unknown]
	at net.minecraft.server.v1_9_R2.PlayerChunkMap.flush(PlayerChunkMap.java:152) ~[Torch.jar:git-Torch-unknown]
	at net.minecraft.server.v1_9_R2.WorldServer.doTick(WorldServer.java:277) ~[Torch.jar:git-Torch-unknown]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:951) ~[Torch.jar:git-Torch-unknown]
	... 4 more
[16:02:00] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.IndexOutOfBoundsException: writerIndex(22598) + minWritableBytes(2048) exceeds maxCapacity(24644): UnpooledHeapByteBuf(ridx: 0, widx: 22598, cap: 24644/24644)
	at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:242) ~[Torch.jar:git-Torch-unknown]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:817) ~[Torch.jar:git-Torch-unknown]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:825) ~[Torch.jar:git-Torch-unknown]
	at net.minecraft.server.v1_9_R2.PacketDataSerializer.writeBytes(PacketDataSerializer.java:755) ~[Torch.jar:git-Torch-unknown]
	at net.minecraft.server.v1_9_R2.PacketPlayOutMapChunk.a(PacketPlayOutMapChunk.java:140) ~[Torch.jar:git-Torch-unknown]
	at com.destroystokyo.paper.antixray.AntiXray.createPacket(AntiXray.java:117) ~[Torch.jar:git-Torch-unknown]
	at net.minecraft.server.v1_9_R2.PacketPlayOutMapChunk.<init>(PacketPlayOutMapChunk.java:35) ~[Torch.jar:git-Torch-unknown]
	at net.minecraft.server.v1_9_R2.PlayerChunk.d(PlayerChunk.java:250) ~[Torch.jar:git-Torch-unknown]
	at net.minecraft.server.v1_9_R2.PlayerChunkMap.flush(PlayerChunkMap.java:152) ~[Torch.jar:git-Torch-unknown]
	at net.minecraft.server.v1_9_R2.WorldServer.doTick(WorldServer.java:277) ~[Torch.jar:git-Torch-unknown]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:951) ~[Torch.jar:git-Torch-unknown]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:412) ~[Torch.jar:git-Torch-unknown]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:829) ~[Torch.jar:git-Torch-unknown]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:722) [Torch.jar:git-Torch-unknown]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

**Comment by SotrForgotten** [comment]
can't reproduce.
