### ISSUE TITLE
Exception on loading NBT data

### ISSUE THREAD

**Issue by SotrForgotten** [TorchSpigot/Torch#25]
```
Description: Loading NBT data

java.util.zip.ZipException: invalid distance too far back
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.torch.util.io.FastBufferedInputStream.noMoreCharacters(FastBufferedInputStream.java:187)
	at org.torch.util.io.FastBufferedInputStream.read(FastBufferedInputStream.java:229)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at net.minecraft.server.v1_9_R2.NBTTagByteArray.load(NBTTagByteArray.java:30)
	at net.minecraft.server.v1_9_R2.NBTTagCompound.a(NBTTagCompound.java:386)
	at net.minecraft.server.v1_9_R2.NBTTagCompound.load(NBTTagCompound.java:46)
	at net.minecraft.server.v1_9_R2.NBTTagList.load(NBTTagList.java:53)
	at net.minecraft.server.v1_9_R2.NBTTagCompound.a(NBTTagCompound.java:386)
	at net.minecraft.server.v1_9_R2.NBTTagCompound.load(NBTTagCompound.java:46)
	at net.minecraft.server.v1_9_R2.NBTTagCompound.a(NBTTagCompound.java:386)
	at net.minecraft.server.v1_9_R2.NBTTagCompound.load(NBTTagCompound.java:46)
	at net.minecraft.server.v1_9_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:84)
	at net.minecraft.server.v1_9_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:53)
	at net.minecraft.server.v1_9_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:43)
	at net.minecraft.server.v1_9_R2.RegionFileCache.c(RegionFileCache.java:93)
	at net.minecraft.server.v1_9_R2.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:84)
	at org.bukkit.craftbukkit.v1_9_R2.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:22)
	at org.bukkit.craftbukkit.v1_9_R2.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:15)
	at org.bukkit.craftbukkit.v1_9_R2.util.AsynchronousExecutor$Task.init(AsynchronousExecutor.java:150)
	at org.bukkit.craftbukkit.v1_9_R2.util.AsynchronousExecutor$Task.initAsync(AsynchronousExecutor.java:95)
	at org.bukkit.craftbukkit.v1_9_R2.util.AsynchronousExecutor$Task.run(AsynchronousExecutor.java:85)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by SotrForgotten** [comment]
can't reprodece, seem that cause by a broken player data
