### ISSUE TITLE
EntityDeathEvent 错误

### ISSUE THREAD

**Issue by ningwang747** [TorchSpigot/Torch#32]
[09:00:52 ERROR]: Could not pass event EntityDeathEvent to CoreProtect v2.13.1
org.bukkit.event.EventException
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[Torch.jar:git-Torch-unknown]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:75) ~[Torch.jar:git-Torch-unknown]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Torch.jar:git-Torch-unknown]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:550) ~[Torch.jar:git-Torch-unknown]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[Torch.jar:git-Torch-unknown]
        at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:485) ~[Torch.jar:git-Torch-unknown]
        at net.minecraft.server.v1_9_R2.EntityLiving.die(EntityLiving.java:1066) ~[Torch.jar:git-Torch-unknown]
        at net.minecraft.server.v1_9_R2.EntityZombie.die(EntityZombie.java:632) ~[Torch.jar:git-Torch-unknown]
        at net.minecraft.server.v1_9_R2.EntityLiving.damageEntity(EntityLiving.java:982) ~[Torch.jar:git-Torch-unknown]
        at net.minecraft.server.v1_9_R2.EntityMonster.damageEntity(EntityMonster.java:50) ~[Torch.jar:git-Torch-unknown]
        at net.minecraft.server.v1_9_R2.EntityZombie.damageEntity(EntityZombie.java:201) ~[Torch.jar:git-Torch-unknown]
        at net.minecraft.server.v1_9_R2.EntityHuman.attack(EntityHuman.java:1105) ~[Torch.jar:git-Torch-unknown]
        at net.minecraft.server.v1_9_R2.EntityPlayer.attack(EntityPlayer.java:1332) ~[Torch.jar:git-Torch-unknown]
        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1870) ~[Torch.jar:git-Torch-unknown]
        at net.minecraft.server.v1_9_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:60) ~[Torch.jar:git-Torch-unknown]
        at net.minecraft.server.v1_9_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:3) ~[Torch.jar:git-Torch-unknown]
        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:10) ~[Torch.jar:git-Torch-unknown]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
        at net.minecraft.server.v1_9_R2.SystemUtils.a(SystemUtils.java:16) [Torch.jar:git-Torch-unknown]
        at net.minecraft.server.v1_9_R2.MinecraftServer.processNetworkQueue(MinecraftServer.java:130) [Torch.jar:git-Torch-unknown]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:919) [Torch.jar:git-Torch-unknown]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:453) [Torch.jar:git-Torch-unknown]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:851) [Torch.jar:git-Torch-unknown]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:740) [Torch.jar:git-Torch-unknown]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
        at org.bukkit.entity.Villager$Profession.getProfession(Villager.java:157) ~[Torch.jar:git-Torch-unknown]
        at org.bukkit.craftbukkit.v1_9_R2.entity.CraftZombie.getVillagerProfession(CraftZombie.java:68) ~[Torch.jar:git-Torch-unknown]
        at net.coreprotect.listener.EntityListener.onEntityDeath(EntityListener.java:405) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor22.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[Torch.jar:git-Torch-unknown]
        ... 24 more

**Comment by SotrForgotten** [comment]
请尝试最新版本。
