### ISSUE TITLE
NullPointerException 异常

### ISSUE THREAD

**Issue by ningwang747** [TorchSpigot/Torch#36]
[04:29:43] [Server thread/WARN]: java.lang.NullPointerException
[04:29:43] [Server thread/WARN]:        at com.plotsquared.bukkit.util.block.GenChunk.fillBiome(GenChunk.java:76)
[04:29:43] [Server thread/WARN]:        at com.intellectualcrafters.plot.generator.HybridGen.generateChunk(HybridGen.java:31)
[04:29:43] [Server thread/WARN]:        at com.plotsquared.bukkit.generator.BukkitPlotGenerator.generate(BukkitPlotGenerator.java:297)
[04:29:43] [Server thread/WARN]:        at com.plotsquared.bukkit.generator.BukkitPlotGenerator.generateChunkData(BukkitPlotGenerator.java:273)
[04:29:43] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_9_R2.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:61)
[04:29:43] [Server thread/WARN]:        at co.aikar.timings.TimedChunkGenerator.getOrCreateChunk(TimedChunkGenerator.java:93)
[04:29:43] [Server thread/WARN]:        at net.minecraft.server.v1_9_R2.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:204)
[04:29:43] [Server thread/WARN]:        at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:186)
[04:29:43] [Server thread/WARN]:        at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:168)
[04:29:43] [Server thread/WARN]:        at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:164)
[04:29:43] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.createWorld(CraftServer.java:1086)
[04:29:43] [Server thread/WARN]:        at org.bukkit.Bukkit.createWorld(Bukkit.java:532)
[04:29:43] [Server thread/WARN]:        at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
[04:29:43] [Server thread/WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:466)
[04:29:43] [Server thread/WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:268)
[04:29:43] [Server thread/WARN]:        at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114)
[04:29:43] [Server thread/WARN]:        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
[04:29:43] [Server thread/WARN]:        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
[04:29:43] [Server thread/WARN]:        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[04:29:43] [Server thread/WARN]:        at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:906)
[04:29:43] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48)
[04:29:43] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:258)
[04:29:43] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:758)
[04:29:43] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchServerCommand(CraftServer.java:716)
[04:29:43] [Server thread/WARN]:        at net.minecraft.server.v1_9_R2.DedicatedServer.aL(DedicatedServer.java:498)
[04:29:43] [Server thread/WARN]:        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:454)
[04:29:43] [Server thread/WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:850)
[04:29:43] [Server thread/WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:739)
[04:29:43] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:745)
[04:29:43] [ForkJoinPool.commonPool-worker-1/WARN]: java.lang.NullPointerException
[04:29:43] [ForkJoinPool.commonPool-worker-1/WARN]:     at com.plotsquared.bukkit.util.block.GenChunk.setBlock(GenChunk.java:109)
[04:29:43] [ForkJoinPool.commonPool-worker-1/WARN]:     at com.intellectualcrafters.plot.util.block.LocalBlockQueue.setBlock(LocalBlockQueue.java:48)
[04:29:43] [ForkJoinPool.commonPool-worker-1/WARN]:     at com.intellectualcrafters.plot.generator.HybridGen.generateChunk(HybridGen.java:143)
[04:29:43] [ForkJoinPool.commonPool-worker-1/WARN]:     at com.plotsquared.bukkit.generator.BukkitPlotGenerator.generate(BukkitPlotGenerator.java:297)
[04:29:43] [ForkJoinPool.commonPool-worker-1/WARN]:     at com.plotsquared.bukkit.generator.BukkitPlotGenerator$1.populate(BukkitPlotGenerator.java:73)
[04:29:43] [ForkJoinPool.commonPool-worker-1/WARN]:     at org.hose.ChunkPopulate_Pool.compute(ChunkPopulate_Pool.java:33)
[04:29:43] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
[04:29:43] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[04:29:43] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[04:29:43] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[04:29:43] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by SotrForgotten** [comment]
能否提供插件文件

**Comment by ningwang747** [comment]
哪几个插件

**Comment by SotrForgotten** [comment]
plotsquared @ningwang747

**Comment by ningwang747** [comment]
http://ci.athion.net/job/PlotSquared/321/artifact/target/PlotSquared-Bukkit-3.4.5-SNAPSHOT-005e13a.jar

**Comment by ningwang747** [comment]
还有那个崩溃报告你处理1下

**Comment by ningwang747** [comment]
这个修复了么

**Comment by SotrForgotten** [comment]
还没有 @ningwang747

**Comment by ningwang747** [comment]
那paper-io的Failed to save chunk呢

**Comment by SotrForgotten** [comment]
@ningwang747 不推荐使用paper-io

**Comment by ningwang747** [comment]
不推荐为什么还要留着呢
