### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by SotrForgotten** [TorchSpigot/Torch#6]
1.9.4-R1.3, can be reproduce

```
[19:57:13] [Netty Server IO #2/FATAL]: Uncaught Exception
java.lang.NullPointerException
	at net.minecraft.server.v1_9_R2.PacketStatusListener.a(PacketStatusListener.java:124) ~[Torch.jar:git-Torch-unknown]
	at net.minecraft.server.v1_9_R2.PacketStatusInStart.a(SourceFile:23) ~[Torch.jar:git-Torch-unknown]
	at net.minecraft.server.v1_9_R2.PacketStatusInStart.a(SourceFile:8) ~[Torch.jar:git-Torch-unknown]
	at net.minecraft.server.v1_9_R2.NetworkManager.a(NetworkManager.java:128) ~[Torch.jar:git-Torch-unknown]
	at net.minecraft.server.v1_9_R2.NetworkManager.channelRead0(NetworkManager.java:338) ~[Torch.jar:git-Torch-unknown]
	at net.minecraft.server.v1_9_R2.NetworkManager.channelRead0(NetworkManager.java:31) ~[Torch.jar:git-Torch-unknown]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[Torch.jar:git-Torch-unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [Torch.jar:git-Torch-unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [Torch.jar:git-Torch-unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [Torch.jar:git-Torch-unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [Torch.jar:git-Torch-unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [Torch.jar:git-Torch-unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [Torch.jar:git-Torch-unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [Torch.jar:git-Torch-unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [Torch.jar:git-Torch-unknown]
	at net.minecraft.server.v1_9_R2.LegacyPingHandler.channelRead(SourceFile:94) [Torch.jar:git-Torch-unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [Torch.jar:git-Torch-unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [Torch.jar:git-Torch-unknown]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [Torch.jar:git-Torch-unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [Torch.jar:git-Torch-unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [Torch.jar:git-Torch-unknown]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [Torch.jar:git-Torch-unknown]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [Torch.jar:git-Torch-unknown]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [Torch.jar:git-Torch-unknown]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [Torch.jar:git-Torch-unknown]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [Torch.jar:git-Torch-unknown]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [Torch.jar:git-Torch-unknown]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [Torch.jar:git-Torch-unknown]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

**Comment by SotrForgotten** [comment]
This will be fix in the next release.
