### ISSUE TITLE
Error org.bukkit.craftbukkit.v1_9_R2.inventory.CraftShapedRecipe.addToCraftingManager

### ISSUE THREAD

**Issue by ASuperthings** [TorchSpigot/Torch#60]
[11:55:12] [Server thread/INFO]: [NewItems] Enabling NewItems v1.1.2
[11:55:13] [Server thread/ERROR]: Error occurred while enabling NewItems v1.1.2 (Is it up to date?)
java.lang.NullPointerException
    at java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source) ~[?:1.8.0_101]
    at java.util.concurrent.ConcurrentHashMap.put(Unknown Source) ~[?:1.8.0_101]
    at net.minecraft.server.v1_9_R2.CraftingManager.registerShapedRecipe(CraftingManager.java:434) ~[Torch-1.9.4-R1.9.1-RELEASE.jar:git-Torch-unknown]
    at org.bukkit.craftbukkit.v1_9_R2.inventory.CraftShapedRecipe.addToCraftingManager(CraftShapedRecipe.java:66) ~[Torch-1.9.4-R1.9.1-RELEASE.jar:git-Torch-unknown]
    at org.bukkit.craftbukkit.v1_9_R2.CraftServer.addRecipe(CraftServer.java:1272) ~[Torch-1.9.4-R1.9.1-RELEASE.jar:git-Torch-unknown]
    at com.evill4mer.NewItems.j.m(Unknown Source) ~[?:?]
    at com.evill4mer.NewItems.Main.onEnable(Unknown Source) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:302) ~[Torch-1.9.4-R1.9.1-RELEASE.jar:git-Torch-unknown]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) [Torch-1.9.4-R1.9.1-RELEASE.jar:git-Torch-unknown]
    at pw.yumc.Yum.inject.YumPluginLoader.enablePlugin(YumPluginLoader.java:119) [Yum.jar:?]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:433) [Torch-1.9.4-R1.9.1-RELEASE.jar:git-Torch-unknown]
    at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugin(CraftServer.java:420) [Torch-1.9.4-R1.9.1-RELEASE.jar:git-Torch-unknown]
    at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:376) [Torch-1.9.4-R1.9.1-RELEASE.jar:git-Torch-unknown]
    at net.minecraft.server.v1_9_R2.MinecraftServer.t(MinecraftServer.java:479) [Torch-1.9.4-R1.9.1-RELEASE.jar:git-Torch-unknown]
    at net.minecraft.server.v1_9_R2.MinecraftServer.l(MinecraftServer.java:443) [Torch-1.9.4-R1.9.1-RELEASE.jar:git-Torch-unknown]
    at net.minecraft.server.v1_9_R2.MinecraftServer.a(MinecraftServer.java:389) [Torch-1.9.4-R1.9.1-RELEASE.jar:git-Torch-unknown]
    at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:283) [Torch-1.9.4-R1.9.1-RELEASE.jar:git-Torch-unknown]
    at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:698) [Torch-1.9.4-R1.9.1-RELEASE.jar:git-Torch-unknown]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
[11:55:13] [Server thread/INFO]: [NewItems] Disabling NewItems v1.1.2
[11:55:13] [Server thread/INFO]: [NewItems] Enabling NewItems v1.1.2
[11:55:13] [Server thread/ERROR]: Error occurred while enabling NewItems v1.1.2 (Is it up to date?)
java.lang.NullPointerException
    at java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source) ~[?:1.8.0_101]
    at java.util.concurrent.ConcurrentHashMap.put(Unknown Source) ~[?:1.8.0_101]
    at net.minecraft.server.v1_9_R2.CraftingManager.registerShapedRecipe(CraftingManager.java:434) ~[Torch-1.9.4-R1.9.1-RELEASE.jar:git-Torch-unknown]
    at org.bukkit.craftbukkit.v1_9_R2.inventory.CraftShapedRecipe.addToCraftingManager(CraftShapedRecipe.java:66) ~[Torch-1.9.4-R1.9.1-RELEASE.jar:git-Torch-unknown]
    at org.bukkit.craftbukkit.v1_9_R2.CraftServer.addRecipe(CraftServer.java:1272) ~[Torch-1.9.4-R1.9.1-RELEASE.jar:git-Torch-unknown]
    at com.evill4mer.NewItems.j.m(Unknown Source) ~[?:?]
    at com.evill4mer.NewItems.Main.onEnable(Unknown Source) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:302) ~[Torch-1.9.4-R1.9.1-RELEASE.jar:git-Torch-unknown]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) [Torch-1.9.4-R1.9.1-RELEASE.jar:git-Torch-unknown]
    at pw.yumc.Yum.inject.YumPluginLoader.enablePlugin(YumPluginLoader.java:119) [Yum.jar:?]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:433) [Torch-1.9.4-R1.9.1-RELEASE.jar:git-Torch-unknown]
    at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugin(CraftServer.java:437) [Torch-1.9.4-R1.9.1-RELEASE.jar:git-Torch-unknown]
    at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:376) [Torch-1.9.4-R1.9.1-RELEASE.jar:git-Torch-unknown]
    at net.minecraft.server.v1_9_R2.MinecraftServer.t(MinecraftServer.java:479) [Torch-1.9.4-R1.9.1-RELEASE.jar:git-Torch-unknown]
    at net.minecraft.server.v1_9_R2.MinecraftServer.l(MinecraftServer.java:443) [Torch-1.9.4-R1.9.1-RELEASE.jar:git-Torch-unknown]
    at net.minecraft.server.v1_9_R2.MinecraftServer.a(MinecraftServer.java:389) [Torch-1.9.4-R1.9.1-RELEASE.jar:git-Torch-unknown]
    at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:283) [Torch-1.9.4-R1.9.1-RELEASE.jar:git-Torch-unknown]
    at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:698) [Torch-1.9.4-R1.9.1-RELEASE.jar:git-Torch-unknown]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
[11:55:13] [Server thread/INFO]: [NewItems] Disabling NewItems v1.1.2
# I can use this plugin well on paper.

But it doesn't work on torch.
Hope to fix.

**Comment by ningwang747** [comment]
您是不是用Yum重新启动了这个插件?

**Comment by ASuperthings** [comment]
没有用yum重新启动,这是在启动服务器的时候 @ningwang747

**Comment by SotrForgotten** [comment]
已经修复了，只是还没有推上来。但是目前正在重新制作新版本(R2)

**Comment by ningwang747** [comment]
outdated version
