### ISSUE TITLE
error on server start

### ISSUE THREAD

**Issue by mat41997** [TorchSpigot/Torch#67]
logs
```
2017-04-27 07:25:48,758 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[ERROR] Terminal initialization failed; falling back to unsupported
[STDERR]: java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.internal.Kernel32
[STDERR]:       at org.fusesource.jansi.internal.WindowsSupport.getConsoleMode(WindowsSupport.java:50)
[STDERR]:       at org.bukkit.craftbukkit.libs.jline.WindowsTerminal.getConsoleMode(WindowsTerminal.java:204)
[STDERR]:       at org.bukkit.craftbukkit.libs.jline.WindowsTerminal.init(WindowsTerminal.java:82)
[STDERR]:       at org.bukkit.craftbukkit.libs.jline.TerminalFactory.create(TerminalFactory.java:101)
[STDERR]:       at org.bukkit.craftbukkit.libs.jline.TerminalFactory.get(TerminalFactory.java:158)
[STDERR]:       at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.<init>(ConsoleReader.java:229)
[STDERR]:       at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.<init>(ConsoleReader.java:221)
[STDERR]:       at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.<init>(ConsoleReader.java:213)
[STDERR]:       at org.torch.server.TorchServer.<init>(TorchServer.java:415)
[STDERR]:       at org.torch.server.TorchServer.<init>(TorchServer.java:444)
[STDERR]:       at net.minecraft.server.v1_11_R1.MinecraftServer.<init>(MinecraftServer.java:253)
[STDERR]:       at net.minecraft.server.v1_11_R1.DedicatedServer.<init>(DedicatedServer.java:80)
[STDERR]:       at org.torch.server.TorchServer.main(TorchServer.java:470)
[STDERR]:       at net.minecraft.server.v1_11_R1.MinecraftServer.main(MinecraftServer.java:436)
[STDERR]:       at org.bukkit.craftbukkit.Main.main(Main.java:226)

[07:25:52 INFO]: [STDERR]: java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.internal.Kernel32
[07:25:52 INFO]: [STDERR]:      at org.fusesource.jansi.internal.WindowsSupport.getConsoleMode(WindowsSupport.java:50)
[07:25:52 INFO]: [STDERR]:      at org.bukkit.craftbukkit.libs.jline.WindowsTerminal.getConsoleMode(WindowsTerminal.java:204)
[07:25:52 INFO]: [STDERR]:      at org.bukkit.craftbukkit.libs.jline.WindowsTerminal.init(WindowsTerminal.java:82)
[07:25:52 INFO]: [STDERR]:      at org.bukkit.craftbukkit.libs.jline.TerminalFactory.create(TerminalFactory.java:101)
[07:25:52 INFO]: [STDERR]:      at org.bukkit.craftbukkit.libs.jline.TerminalFactory.get(TerminalFactory.java:158)
[07:25:52 INFO]: [STDERR]:      at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.<init>(ConsoleReader.java:229)
[07:25:52 INFO]: [STDERR]:      at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.<init>(ConsoleReader.java:221)
[07:25:52 INFO]: [STDERR]:      at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.<init>(ConsoleReader.java:213)
[07:25:52 INFO]: [STDERR]:      at org.torch.server.TorchServer.<init>(TorchServer.java:415)
[07:25:52 INFO]: [STDERR]:      at org.torch.server.TorchServer.<init>(TorchServer.java:444)
[07:25:52 INFO]: [STDERR]:      at net.minecraft.server.v1_11_R1.MinecraftServer.<init>(MinecraftServer.java:253)
[07:25:52 INFO]: [STDERR]:      at net.minecraft.server.v1_11_R1.DedicatedServer.<init>(DedicatedServer.java:80)
[07:25:52 INFO]: [STDERR]:      at org.torch.server.TorchServer.main(TorchServer.java:470)
[07:25:52 INFO]: [STDERR]:      at net.minecraft.server.v1_11_R1.MinecraftServer.main(MinecraftServer.java:436)
[07:25:52 INFO]: [STDERR]:      at org.bukkit.craftbukkit.Main.main(Main.java:226)
[07:25:52 INFO]: Starting minecraft server version 1.11.2
```

timings
https://timings.aikar.co/?id=c42b2f0a920243f7af01028bae9624c0

windows 10 pro x64

java
8 131 x64

build - 46
https://circleci.com/gh/TorchSpigot/Torch/46

**Comment by SotrForgotten** [comment]
Ensure Microsoft Visual C++ 2008 SP1 Redistributable, has installed correctly, or simply add '--nojline' arguments to your launch scripts.

**Comment by SotrForgotten** [comment]
Try adding:
-Dlibrary.jansi.version=Torch

**Comment by SotrForgotten** [comment]
Latest build fixed this, for further info: https://github.com/PaperMC/Paper/issues/696
