### ISSUE TITLE
authme error - torchspigot issue

### ISSUE THREAD

**Issue by mat41997** [TorchSpigot/Torch#69]
logs
```
[10:18:25] [Craft Scheduler Thread - 2/INFO]: [AuthMe] QiiQii logged in!
[10:18:25] [Server thread/WARN]: [AuthMe] Task #909 for AuthMe v5.3-SNAPSHOT-b1659 generated an exception
java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.saveData(CraftPlayer.java:643) ~[Torchpowered-1.11.2.jar:git-Torch-"0e018f9"]
	at fr.xephi.authme.process.login.ProcessSyncPlayerLogin.processPlayerLogin(ProcessSyncPlayerLogin.java:95) ~[?:?]
	at fr.xephi.authme.process.SyncProcessManager.lambda$processSyncPlayerLogin$3(SyncProcessManager.java:51) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[Torchpowered-1.11.2.jar:git-Torch-"0e018f9"]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [Torchpowered-1.11.2.jar:git-Torch-"0e018f9"]
	at org.torch.server.TorchServer.updateLogicsAndPhysics(TorchServer.java:900) [Torchpowered-1.11.2.jar:git-Torch-"0e018f9"]
	at org.torch.server.TorchServer.updateLogicsPhysicsExecuteCommands(TorchServer.java:1659) [Torchpowered-1.11.2.jar:git-Torch-"0e018f9"]
	at org.torch.server.TorchServer.tick(TorchServer.java:851) [Torchpowered-1.11.2.jar:git-Torch-"0e018f9"]
	at org.torch.server.TorchServer.run(TorchServer.java:542) [Torchpowered-1.11.2.jar:git-Torch-"0e018f9"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

timings
https://timings.aikar.co/?id=8df88eec512649509a177559d30a7dd0

torchspigot
https://circleci.com/gh/TorchSpigot/Torch/94#artifacts/containers/0

authme
http://ci.xephi.fr/job/AuthMeReloaded/1659/

other
https://github.com/AuthMe/AuthMeReloaded/issues/1184

**Comment by SotrForgotten** [comment]
Try latest build, reopen this if still occurred.
