### ISSUE TITLE
error on startup 

### ISSUE THREAD

**Issue by Dimatert9** [TorchSpigot/Torch#84]
```
[12:55:02] [main/INFO]: [STDERR]: java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.internal.Kernel32
[12:55:02] [main/INFO]: [STDERR]: 	at org.fusesource.jansi.internal.WindowsSupport.getConsoleMode(WindowsSupport.java:50)
[12:55:02] [main/INFO]: [STDERR]: 	at org.bukkit.craftbukkit.libs.jline.WindowsTerminal.getConsoleMode(WindowsTerminal.java:204)
[12:55:02] [main/INFO]: [STDERR]: 	at org.bukkit.craftbukkit.libs.jline.WindowsTerminal.init(WindowsTerminal.java:82)
[12:55:02] [main/INFO]: [STDERR]: 	at org.bukkit.craftbukkit.libs.jline.TerminalFactory.create(TerminalFactory.java:101)
[12:55:02] [main/INFO]: [STDERR]: 	at org.bukkit.craftbukkit.libs.jline.TerminalFactory.get(TerminalFactory.java:158)
[12:55:02] [main/INFO]: [STDERR]: 	at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.<init>(ConsoleReader.java:229)
[12:55:02] [main/INFO]: [STDERR]: 	at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.<init>(ConsoleReader.java:221)
[12:55:02] [main/INFO]: [STDERR]: 	at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.<init>(ConsoleReader.java:213)
[12:55:02] [main/INFO]: [STDERR]: 	at org.torch.server.TorchServer.<init>(TorchServer.java:422)
[12:55:02] [main/INFO]: [STDERR]: 	at org.torch.server.TorchServer.<init>(TorchServer.java:451)
[12:55:02] [main/INFO]: [STDERR]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.<init>(MinecraftServer.java:254)
[12:55:02] [main/INFO]: [STDERR]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.<init>(DedicatedServer.java:76)
[12:55:02] [main/INFO]: [STDERR]: 	at org.torch.server.TorchServer.main(TorchServer.java:477)
[12:55:02] [main/INFO]: [STDERR]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.main(MinecraftServer.java:437)
[12:55:02] [main/INFO]: [STDERR]: 	at org.bukkit.craftbukkit.Main.main(Main.java:225)
[12:55:02] [Server thread/INFO]: Starting minecraft server version 1.11.2
[12:55:02] [Server thread/INFO]: Default game type: SURVIVAL
[12:55:02] [Server thread/INFO]: This server is running Torch version git-Torch-"c5f5646" (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
[12:55:05] [Server thread/INFO]: Binding server to *:25565
[12:55:05] [Server thread/INFO]: Using default channel type
[12:55:05] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[12:55:05] [Server thread/INFO]: Beginning UUID conversion, this may take A LONG time
[12:55:06] [Server thread/INFO]: Preparing level "world"
[12:55:09] [Server thread/INFO]: Preparing start region for level 0 (Seed: -221273909080531318)
[12:55:10] [Server thread/INFO]: Preparing spawn area: 3%
[12:55:12] [Server thread/INFO]: Preparing spawn area: 4%
[12:55:13] [Server thread/INFO]: Preparing spawn area: 12%
[12:55:14] [Server thread/INFO]: Preparing spawn area: 21%
[12:55:15] [Server thread/INFO]: Preparing spawn area: 30%
[12:55:16] [Server thread/INFO]: Preparing spawn area: 43%
[12:55:16] [Server thread/INFO]: Preparing start region for level -1 (Seed: -221273909080531318)
[12:55:17] [Server thread/INFO]: Preparing spawn area: 15%
[12:55:18] [Server thread/INFO]: Preparing spawn area: 34%
[12:55:19] [Server thread/INFO]: Preparing start region for level 1 (Seed: -221273909080531318)
[12:55:20] [Server thread/INFO]: Preparing spawn area: 38%
[12:55:20] [Server thread/INFO]: Ready for connections! (14,622s)
[12:55:20] [Server thread/INFO]: Timings Reset
```
windows 7.

**Comment by mat41997** [comment]
i have this same error
https://github.com/TorchSpigot/Torch/issues/67
