### ISSUE TITLE
LibsDisguises throws a lot of errors with Torch

### ISSUE THREAD

**Issue by MrPowerGamerBR** [TorchSpigot/Torch#93]
```
[20:18:30] [Server thread/ERROR]: [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
java.lang.RuntimeException: Cannot retrieve entity from ID.
	at com.comphenix.protocol.wrappers.BukkitConverters$13.getSpecificValue(BukkitConverters.java:701) ~[ProtocolLib.jar:4.2.2-SNAPSHOT-b357]
	at com.comphenix.protocol.wrappers.BukkitConverters$13.getSpecificValue(BukkitConverters.java:680) ~[ProtocolLib.jar:4.2.2-SNAPSHOT-b357]
	at com.comphenix.protocol.wrappers.BukkitConverters$IgnoreNullConverter.getSpecific(BukkitConverters.java:148) ~[ProtocolLib.jar:4.2.2-SNAPSHOT-b357]
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:230) ~[ProtocolLib.jar:4.2.2-SNAPSHOT-b357]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:198) ~[ProtocolLib.jar:4.2.2-SNAPSHOT-b357]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.WrapperPlayServerEntityMetadata.getEntity(WrapperPlayServerEntityMetadata.java:65) ~[HolographicDisplays.jar:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.WrapperPlayServerEntityMetadata.getEntity(WrapperPlayServerEntityMetadata.java:74) ~[HolographicDisplays.jar:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:164) ~[HolographicDisplays.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.2.2-SNAPSHOT-b357]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.2.2-SNAPSHOT-b357]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:608) [ProtocolLib.jar:4.2.2-SNAPSHOT-b357]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:584) [ProtocolLib.jar:4.2.2-SNAPSHOT-b357]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:309) [ProtocolLib.jar:4.2.2-SNAPSHOT-b357]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:269) [ProtocolLib.jar:4.2.2-SNAPSHOT-b357]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:396) [ProtocolLib.jar:4.2.2-SNAPSHOT-b357]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77) [ProtocolLib.jar:4.2.2-SNAPSHOT-b357]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:362) [ProtocolLib.jar:4.2.2-SNAPSHOT-b357]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:330) [ProtocolLib.jar:4.2.2-SNAPSHOT-b357]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.2.2-SNAPSHOT-b357]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.2.2-SNAPSHOT-b357]
	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:208) [paperclip.jar:git-Torch-"bffe8ff"]
	at net.minecraft.server.v1_11_R1.NetworkManager.sendPacket(NetworkManager.java:151) [paperclip.jar:git-Torch-"bffe8ff"]
	at net.minecraft.server.v1_11_R1.PlayerConnection.sendPacket(PlayerConnection.java:1125) [paperclip.jar:git-Torch-"bffe8ff"]
	at net.minecraft.server.v1_11_R1.EntityTrackerEntry.broadcastIncludingSelf(EntityTrackerEntry.java:325) [paperclip.jar:git-Torch-"bffe8ff"]
	at net.minecraft.server.v1_11_R1.EntityTrackerEntry.d(EntityTrackerEntry.java:290) [paperclip.jar:git-Torch-"bffe8ff"]
	at net.minecraft.server.v1_11_R1.EntityTrackerEntry.track(EntityTrackerEntry.java:232) [paperclip.jar:git-Torch-"bffe8ff"]
	at net.minecraft.server.v1_11_R1.EntityTracker.updatePlayers(EntityTracker.java:186) [paperclip.jar:git-Torch-"bffe8ff"]
	at org.torch.server.TorchServer.updateLogicsAndPhysics(TorchServer.java:972) [paperclip.jar:git-Torch-"bffe8ff"]
	at org.torch.server.TorchServer.updateLogicsPhysicsExecuteCommands(TorchServer.java:1664) [paperclip.jar:git-Torch-"bffe8ff"]
	at org.torch.server.TorchServer.tick(TorchServer.java:855) [paperclip.jar:git-Torch-"bffe8ff"]
	at org.torch.server.TorchServer.run(TorchServer.java:551) [paperclip.jar:git-Torch-"bffe8ff"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: com.comphenix.protocol.reflect.FieldAccessException: Cannot find entity from ID 818.
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:236) ~[ProtocolLib.jar:4.2.2-SNAPSHOT-b357]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:953) ~[ProtocolLib.jar:4.2.2-SNAPSHOT-b357]
	at com.comphenix.protocol.wrappers.BukkitConverters$13.getSpecificValue(BukkitConverters.java:695) ~[ProtocolLib.jar:4.2.2-SNAPSHOT-b357]
	... 31 more
Caused by: java.lang.IllegalArgumentException: Unable to find a field trackedEntities with the type net.minecraft.server.v1_11_R1.IntHashMap in net.minecraft.server.v1_11_R1.EntityTracker
	at com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:400) ~[ProtocolLib.jar:4.2.2-SNAPSHOT-b357]
	at com.comphenix.protocol.injector.EntityUtilities.getEntityTrackerEntry(EntityUtilities.java:189) ~[ProtocolLib.jar:4.2.2-SNAPSHOT-b357]
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:211) ~[ProtocolLib.jar:4.2.2-SNAPSHOT-b357]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:953) ~[ProtocolLib.jar:4.2.2-SNAPSHOT-b357]
	at com.comphenix.protocol.wrappers.BukkitConverters$13.getSpecificValue(BukkitConverters.java:695) ~[ProtocolLib.jar:4.2.2-SNAPSHOT-b357]
	... 31 more
[20:18:30] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_11_R1.PacketPlayOutEntityMetadata@7a4b40a0[
    a=818
    b=[net.minecraft.server.v1_11_R1.DataWatcher$Item@22ec998e, net.minecraft.server.v1_11_R1.DataWatcher$Item@6d86a232, net.minecraft.server.v1_11_R1.DataWatcher$Item@5af2a07d, net.minecraft.server.v1_11_R1.DataWatcher$Item@7a1cb5c3, net.minecraft.server.v1_11_R1.DataWatcher$Item@3c7a73e7, net.minecraft.server.v1_11_R1.DataWatcher$Item@6435d168, net.minecraft.server.v1_11_R1.DataWatcher$Item@2b8b74db, net.minecraft.server.v1_11_R1.DataWatcher$Item@34a67ec4, net.minecraft.server.v1_11_R1.DataWatcher$Item@5bacd6fc, net.minecraft.server.v1_11_R1.DataWatcher$Item@1158e270, net.minecraft.server.v1_11_R1.DataWatcher$Item@6185712c, net.minecraft.server.v1_11_R1.DataWatcher$Item@66d27386, net.minecraft.server.v1_11_R1.DataWatcher$Item@5b745296, net.minecraft.server.v1_11_R1.DataWatcher$Item@d6960ea, net.minecraft.server.v1_11_R1.DataWatcher$Item@472f6c7a]
  ]
```

(Also, wow @SotrForgotten! You are fixing reported issues very fast! And wow, Torch still uses my small patch I made for my 1.7.10 PaperSpigot fork https://github.com/TorchSpigot/Torch/blob/master/sources/src/main/java/org/torch/util/random/LightRandom.java )

**Comment by ningwang747** [comment]
Should be fixed, try latest build.
